name: example
description: BLoC pattern samples.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  flutter_bloc_patterns:
    path: ../
  http: ^0.13.3
  infinite_widgets: ^2.0.0
  lint: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
