name: flutter_bloc_patterns
description: A set of most common BLoC use cases build on top of flutter_bloc library.
version: 0.7.0
homepage: https://github.com/klisiewicz/flutter-bloc-patterns

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^1.2.5
  bloc: ^5.0.1
  flutter_bloc: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^6.0.1
  lint: ^1.3.0
  mockito: ^4.1.1
