name: flutter_bloc_patterns
description: A set of most common BLoC use cases build on top of flutter_bloc library.
version: 0.9.0
homepage: https://github.com/klisiewicz/flutter-bloc-patterns

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.3.0
  mockito: ^4.1.4
