name: flutter_bloc_patterns
description: A set of most common BLoC use cases build on top of flutter_bloc library.
version: 0.9.0
homepage: https://github.com/klisiewicz/flutter-bloc-patterns

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  bloc: ^7.0.0
  equatable: ^2.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^7.0.0

dev_dependencies:
  bloc_test: ^8.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.5.3
  mocktail: ^0.1.2
