name: flutter_bloc_patterns
description: A set of most common BLoC use cases build on top of flutter_bloc library.
version: 0.2.0
author: Karol Lisiewicz <karol.lisiewicz@gmail.com>
homepage: https://github.com/klisiewicz/flutter-bloc-patterns

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  equatable: ^0.6.1
  bloc: ^0.16.1
  flutter_bloc: ^0.22.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
flutter:
